version: '3'
services:

  maven:
    image: maven:3.6-alpine
    dockerfile: ./maven/Dockerfile
    volumes:
      - ./war:/war
  tomcat:
    image: tomcat:9.0.63-jre8-openjdk-slim-buster
    volumes:
      - ./war:/usr/local/tomcat/webapps/
    ports:
      - 8888:8080
    depends_on:
      - maven


#volumes:
#  war:
#&& mvn -f /git/pom.xml package \