version: '3'
services:

  maven:
    image: maven:3.6-alpine
    volumes:
      - war:/war
    command: > 
      /bin/bash -c "apk update \
      && apk add git \
      && git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git git \
      && mvn -f /git/pom.xml package \
      && cp ./git/target/*.war /war/"
  tomcat:
    image: tomcat:9.0.63-jre8-openjdk-slim-buster
    volumes:
      - war:/usr/local/tomcat/webapps
    ports:
      - 8888:8080
    depends_on:
      - maven

volumes:
  war: